### ISSUE TITLE
Matrix Tools web page freezes 

### ISSUE THREAD

**Issue by ebrady1** [FalconChristmas/fpp-matrixtools#2]
Matrix tools is not workung correctly.  The webpage freezes on access, and must be manually killed.  This behavior happens 100% of the time.  The lockup appears to be related to the web page only,  the Pi and fppd remain functional and do not have to be restarted.  

I am running v1.8 on a Pi-3 with the "maxcpu=1" change. Message Queue Aggregator, Message Queue to Matrix Overlay, Weather, and Crontab Editors installed.    I have tried uninstalling and reinstalling each plugin as mentioned somewhere on the forums.   The Pi-3 has a wireless dongle installed, which is the primary means of access.  Eth0 is directly connected to a Advatek Pixlite 4 controller. 

Pixel overlay is configured for a 48x48 Matrix. Playing a sequence through the Pi works correctly on the matrix.

**Comment by ebrady1** [comment]
One other item,  I have tried this with different versions of Chrome and IE on two different PCs and on my Galaxy S6 with the same results.

**Comment by Ceer123** [comment]
Appears to be an issue when your matrix is greater than 740 pxiels.  Added the following "if" lines to matrixtools.php to protect an infinite loop.

```
xsize = parseInt(740 / blockList[blockName].width);
if (xsize == 0) xsize = 4;
ysize = parseInt(370 / blockList[blockName].height);
if (ysize == 0) ysize = 4;
```

**Comment by cpinkham** [comment]
Believe this was fixed a while ago and we have limits in the current code.
