### ISSUE TITLE
Matrix tools plugin not working in 2.7.x

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp-matrixtools#3]
I have never been able to get this to work in much earlier versions and gave up but after last nights XEssentils they used this so I know it works on a BBB it seems

I have a Pi3B+ connected to a color light card and my matrix works great but can't seem to select a matrix in the plugin to type on the screen or draw
<img width="1183" alt="Screen Shot 2019-05-23 at 4 22 00 PM" src="https://user-images.githubusercontent.com/40632971/58283842-61637900-7d77-11e9-860f-de5412e9c647.png">

<img width="1164" alt="Screen Shot 2019-05-23 at 4 26 05 PM" src="https://user-images.githubusercontent.com/40632971/58283893-7c35ed80-7d77-11e9-8329-70501a871713.png">

**Comment by cpinkham** [comment]
Have you configured a FPP Pixel Overlay Model for your matrix?

On Thu, 2019-05-23 at 13:25 -0700, bchiaino wrote:
> > > I have never been able to get this to work in much earlier versions
and gave up but after last nights XEssentils they used this so I know
it works on a BBB it seems
> > I have a Pi3B+ connected to a color light card and my matrix works
great but can't seem to select a matrix in the
> 
> 
> 
> plugin to type on the screen or draw
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> [
> {
> > "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> > > > "target": "https://github.com/FalconChristmas/fpp-matrixtools/issues/
3?email_source=notifications\u0026email_token=AADT72A4SH34U6NIMHPWD4L
PW34TZA5CNFSM4HPJ7ZDKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM
4GVRYI3A",
> > > > "url": "https://github.com/FalconChristmas/fpp-matrixtools/issues/3?e
mail_source=notifications\u0026email_token=AADT72A4SH34U6NIMHPWD4LPW3
4TZA5CNFSM4HPJ7ZDKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GV
RYI3A",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> > "url": "https://github.com"
> }
> }
> ]

**Comment by bchiaino** [comment]
yes but its a little confusing on the string and strand area

I have a matrix that's 192 pixels wide by 144 high (54 - P10 panels) with 82944 channels but no matter how I try and add the overlay it doesn't show up right in the matrix tool drop down area to select

**Comment by cpinkham** [comment]
Closing as this is an old version and the MatrixTools was updated to work with current FPP v3.x and up using the new built-in pixel overlay code and REST API.
