### ISSUE TITLE
Draw Screen isn't Visible for Virtual Matrix

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp-matrixtools#4]
Tried multiple browsers and they all have the same end result.  If I select my virtual matrix the black box that I can draw on goes away.  If I select a different prop it re-appears.  The text effect does work.  On the draw tab the fill effect works too.

**Comment by Cassock** [comment]
Same issue here with a physical matrix using v4.5.1-2-g7c283b1a (v4.5 branch) and the latest MatrixTools (at least as of this writing)

**Comment by MrPaulAR** [comment]
My issue was resolved by properly defining my matrix in the pixel overlay models.  Check the models box in FPP connect or manually do it.
